// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0R4boDvk4VYqJVf4XgcnWGbYhQGeQKM',
    appId: '1:876989645094:android:7cada2140ea21bea4341e7',
    messagingSenderId: '876989645094',
    projectId: 'ditonton-40576',
    storageBucket: 'ditonton-40576.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFlNdvJ-7CVoEWiObjHdwtzukuLx61L4s',
    appId: '1:876989645094:ios:b9a682d6817e985d4341e7',
    messagingSenderId: '876989645094',
    projectId: 'ditonton-40576',
    storageBucket: 'ditonton-40576.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZD1qPIYWR-eeAcAnzPaSsdtLbdWh5Sxk',
    appId: '1:876989645094:web:99911215da9a9a844341e7',
    messagingSenderId: '876989645094',
    projectId: 'ditonton-40576',
    authDomain: 'ditonton-40576.firebaseapp.com',
    storageBucket: 'ditonton-40576.firebasestorage.app',
    measurementId: 'G-ZGBLR4DTSX',
  );

}